// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallCompare(arg1, arg2) {
  return window['go']['main']['App']['CallCompare'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MessageBox(arg1) {
  return window['go']['main']['App']['MessageBox'](arg1);
}

export function SelectNew(arg1) {
  return window['go']['main']['App']['SelectNew'](arg1);
}

export function SelectOld(arg1) {
  return window['go']['main']['App']['SelectOld'](arg1);
}

export function SelectOldFolder() {
  return window['go']['main']['App']['SelectOldFolder']();
}
